apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashapp
  labels:
    app: ashapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ashapp
  template:
    metadata:
      labels:
        app: ashapp
    spec:
      containers:
      - name: ashapp
        image: <ECR_REPOSITORY_URL>:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: AWS_REGION
          value: "us-east-1"
