name: Build -> Push -> Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERFILE_PATH: ./Dockerfile
  K8S_MANIFEST_DIR: ./k8s
  DEPLOYMENT_NAME: ashapp
  DEPLOYMENT_CONTAINER_NAME: ashapp
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 267092042432
  ECR_REPOSITORY_URL: 267092042432.dkr.ecr.us-east-1.amazonaws.com/ashapp

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.build.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v1

      - id: build
        run: |
          TAG="sha-${GITHUB_SHA::8}"
          docker build -t ${ECR_REPOSITORY_URL}:${TAG} -f ${{ env.DOCKERFILE_PATH }} .
          docker tag ${ECR_REPOSITORY_URL}:${TAG} ${ECR_REPOSITORY_URL}:latest
          docker push ${ECR_REPOSITORY_URL}:${TAG}
          docker push ${ECR_REPOSITORY_URL}:latest
          echo "image_uri=${ECR_REPOSITORY_URL}:${TAG}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: azure/setup-kubectl@v4
        with:
          version: '1.27.0'

      - run: |
          aws eks update-kubeconfig --name your-eks-cluster-name --region ${{ env.AWS_REGION }}

      - run: |
          for i in {1..30}; do
            if kubectl get nodes 2>/dev/null | grep -q " Ready "; then
              break
            fi
            sleep 10
          done

      - run: |
          IMAGE_URI="${{ needs.build_and_push.outputs.image_uri }}"
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
            ${{ env.DEPLOYMENT_CONTAINER_NAME }}=${IMAGE_URI} --record || true
          kubectl apply -f ${{ env.K8S_MANIFEST_DIR }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} --timeout=180s
