name: Terraform -> Build -> Push -> Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TF_WORKING_DIR: terraform
  DOCKERFILE_PATH: ./Dockerfile
  K8S_MANIFEST_DIR: ./k8s
  DEPLOYMENT_NAME: ashapp
  DEPLOYMENT_CONTAINER_NAME: ashapp
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 267092042432

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      ecr_repository_url: ${{ steps.get-outputs.outputs.ecr_repository_url }}
      eks_cluster_name: ${{ steps.get-outputs.outputs.eks_cluster_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: get-outputs
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          ECR_URL=$(terraform output -raw ecr_repository_url 2>/dev/null | tr -d '\r')
          CLUSTER_NAME=$(terraform output -raw eks_cluster_name 2>/dev/null | tr -d '\r')
          echo "ecr_repository_url=${ECR_URL}" >> $GITHUB_OUTPUT
          echo "eks_cluster_name=${CLUSTER_NAME}" >> $GITHUB_OUTPUT

  build_and_push:
    runs-on: ubuntu-latest
    needs: terraform
    outputs:
      image_uri: ${{ steps.build.outputs.image_uri }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r backend/requirements.txt

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        id: build
        run: |
          ECR_URL="${{ needs.terraform.outputs.ecr_repository_url }}"
          TAG="sha-${GITHUB_SHA::8}"
          docker build -t ${ECR_URL}:${TAG} -f ${{ env.DOCKERFILE_PATH }} .
          docker tag ${ECR_URL}:${TAG} ${ECR_URL}:latest
          docker push ${ECR_URL}:${TAG}
          docker push ${ECR_URL}:latest
          echo "image_uri=${ECR_URL}:${TAG}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: [terraform, build_and_push]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: '1.27.0'

      - name: Wait for EKS Cluster to be Ready
        run: |
          echo "Waiting for EKS cluster to be active..."
          for i in {1..30}; do
            STATUS=$(aws eks describe-cluster --name "${{ needs.terraform.outputs.eks_cluster_name }}" --region "${{ env.AWS_REGION }}" --query "cluster.status" --output text || echo "NOT_FOUND")
            if [ "$STATUS" == "ACTIVE" ]; then
              echo "✅ EKS cluster is active!"
              break
            fi
            echo "⏳ Still waiting for EKS cluster..."
            sleep 20
          done

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name "${{ needs.terraform.outputs.eks_cluster_name }}" \
            --region "${{ env.AWS_REGION }}"

      - name: Wait for EKS Nodes to be Ready
        run: |
          echo "Waiting for nodes to be ready..."
          for i in {1..30}; do
            if kubectl get nodes 2>/dev/null | grep -q "Ready"; then
              echo "✅ Nodes are ready!"
              kubectl get nodes
              break
            fi
            echo "⏳ Still waiting for nodes..."
            sleep 10
          done

      - name: Create AWS credentials secret in EKS
        run: |
          kubectl create secret generic aws-credentials \
            --from-literal=aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to EKS
        run: |
          IMAGE_URI="${{ needs.build_and_push.outputs.image_uri }}"
          kubectl -n default set image deployment/${{ env.DEPLOYMENT_NAME }} \
            ${{ env.DEPLOYMENT_CONTAINER_NAME }}=${IMAGE_URI} --record || true
          kubectl apply -f ${{ env.K8S_MANIFEST_DIR }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} --timeout=180s
